### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ancan** [maschhoff/docker#10]
Running this on unRAID, and it slowly eats up the allocated RAM and then it stops.

**Comment by maschhoff** [comment]
Which docker are you running? because this repo contains all my docker stuff

**Comment by ancan** [comment]
Oh, it's the Tor node.

Den ons 5 jan. 2022 16:22Mathias Aschhoff ***@***.***> skrev:

**Comment by maschhoff** [comment]
Ah okay, please refer to https://github.com/DarkIsDude/tor-server its his docker I created only a unraid template for it.

**Comment by ancan** [comment]
Thanks! Will do

Den ons 5 jan. 2022 16:46Mathias Aschhoff ***@***.***> skrev:

**Comment by maschhoff** [comment]
related to the docker
